version: '3.9'
services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/myapp
    # env_file:
    #   - .env
    ports:
      - 8000:8000
    command: sleep infinity
    depends_on:
      - db

  db:
    image: postgres:15.3
    volumes:
      - /data/postgres15:/var/lib/postgresql/data
    user: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    # ports:
    #   - 5432:5432

  

 