# Generated by Django 4.2.7 on 2023-11-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0003_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('online', 'Online Event'), ('offline', 'Offline Event')], max_length=10),
        ),
    ]
